### ISSUE TITLE
Technology Selection

### ISSUE THREAD

**Issue by VoyTechnology** [RazoftOSS/Arbiter#1]
The final technology selection for the project

**Comment by VoyTechnology** [comment]
I would vote to use the upcoming aHACKeal framework

**Comment by GoldenBadger** [comment]
I agree. I'd like to try a new language anyway.

**Comment by GoldenBadger** [comment]
I'd like to add here that I think Django would be a good choice. Even though I'd prefer to use something I've never used before, Django is the way to go. With Django, a tournament run by a small chess club can literally install and run Arbiter with one script, and then access the UI by pointing their browser to localhost. For larger tournaments we can have a configuration file which people can configure to set up Arbiter to run on a public server, with tools like Gunicorn and (if they want) Nginx. Even though other languages and frameworks can accomplish the latter just fine, I don't think any of them have the range between small and large scale that Python+Django has.

**Comment by VoyTechnology** [comment]
@GoldenBadger We always have the option with using node.js and Express.

**Comment by GoldenBadger** [comment]
But is that a 1-script install? Especially with them having to install MongoDB. Not to mention that the base size of a MongoDB database is huge.

**Comment by VoyTechnology** [comment]
Nobody said we have to use MongoDB. Writing things as files is also an option. We can write JSON document and read/write as needed

**Comment by GoldenBadger** [comment]
Then that sounds interesting. We should consider that. Although personally I would prefer something with better object orientation.

**Comment by VoyTechnology** [comment]
I still think that PHP/Hack would be a better option, possibly PHP, as I would guess that they already have their websites, and PHP can be hosted on shared hosting, which is also a huge benefit

**Comment by GoldenBadger** [comment]
That is a very good point, as most clubs would be on shared hosting. Let's go with PHP and see how it goes.

**Comment by VoyTechnology** [comment]
So does that wrap up the backend technolog selection? We are sticking with **PHP**

**Comment by GoldenBadger** [comment]
Yep sounds good. Would you like to do the honours and close the issue?

**Comment by VoyTechnology** [comment]
We still have to decide on the front end framework. I propose Angular.js

**Comment by GoldenBadger** [comment]
I agree. It's very popular and dependency-light.

**Comment by VoyTechnology** [comment]
For our technology selection we will be using:

Front-end: **Angular.js**
Back-end: **PHP** (probably in-house aPHPeal)
